const config = {
  APP_NAME: 'Training',
  BASE_URL: import.meta.env.VITE_BASE_URL,
  LOCAL_PROFILE: 'TRAINING_PROFILE',
  LOCAL_AUTHENTICATED: 'TRAINING_AUTHENTICATED',
  LOCAL_ACCESS_TOKEN: 'TRAINING_ACCESS_TOKEN',
  LOCAL_REFRESH_TOKEN: 'TRAINING_REFRESH_TOKEN',
  LOCAL_LOGIN_TYPE: 'TRAINING_LOGIN_TYPE',
  TIMEOUT: 50000,
  PAGE_SIZE: 500,
  TENANT_URL: 'https://htpa.sharepoint.com',
  EHS_GEMBA_SITE: 'https://htpa.sharepoint.com/Projects/EHS-GEMBA',
  LAST_VERSION: '2024-04-25 17:00',
  IN_TEST: import.meta.env.VITE_IN_TEST === 'Yes',
  IGNORE_MAIL: false
}

export default config
